<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../../Protos/inspection_evaluation.proto" GrpcServices="Server" Link="Protos/inspection_evaluation.proto" />
  </ItemGroup>

</Project>
