using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using UavPms.OperationsService.Infrastructure.Persistence;

#nullable disable

namespace UavPms.OperationsService.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260913065455_AddPreMissionAssessmentAndDroneTechnicalReadinessV2")]
public partial class AddPreMissionAssessmentAndDroneTechnicalReadinessV2 : Migration
{
    protected override void Up(MigrationBuilder m)
    {
        m.AddColumn<string>("OperationalStatus", "UAVs", nullable:false, defaultValue:"Available");
        m.AddColumn<string>("TechnicalHealth", "UAVs", nullable:false, defaultValue:"Unknown");
        m.AddColumn<Guid>("PreMissionAssessmentId", "Missions", nullable:true);
        m.CreateTable("PreMissionAssessments", columns: t => new { Id=t.Column<Guid>("uuid"), ManagerId=t.Column<Guid>("uuid"), RegionId=t.Column<Guid>("uuid"), PlannedStart=t.Column<DateTime>("timestamptz"), PlannedEnd=t.Column<DateTime>("timestamptz"), ProposedBoundary=t.Column<string>("geometry(Geometry,4326)"), Status=t.Column<string>("text"), OverallTechnicalHealth=t.Column<string>("text"), ValidUntil=t.Column<DateTime>("timestamptz"), ConsumedByMissionId=t.Column<Guid>("uuid"), Version=t.Column<long>("bigint"), Findings=t.Column<string>("jsonb"), CreatedAt=t.Column<DateTime>("timestamptz"), UpdatedAt=t.Column<DateTime>("timestamptz"), CreatedBy=t.Column<Guid>("uuid"), UpdatedBy=t.Column<Guid>("uuid"), IsDeleted=t.Column<bool>("boolean"), DeletedAt=t.Column<DateTime>("timestamptz") }, constraints: t=> { t.PrimaryKey("PK_PreMissionAssessments",x=>x.Id); t.CheckConstraint("CK_PreMissionAssessments_PlannedWindow", "\"PlannedEnd\" > \"PlannedStart\""); t.ForeignKey("FK_PreMissionAssessments_Users_ManagerId",x=>x.ManagerId,"Users","Id",onDelete:ReferentialAction.Restrict); t.ForeignKey("FK_PreMissionAssessments_Regions_RegionId",x=>x.RegionId,"Regions","Id",onDelete:ReferentialAction.Restrict); });
        // Asset records are owned by the asset service and are not present in every Operations DB.
        // Keep the UUID reference, but do not create a cross-service FK here.
        m.CreateTable("PreMissionAssessmentAssets", columns: t => new { Id=t.Column<Guid>("uuid"), AssessmentId=t.Column<Guid>("uuid"), AssetId=t.Column<Guid>("uuid"), Sequence=t.Column<int>("integer"), CreatedAt=t.Column<DateTime>("timestamptz"), UpdatedAt=t.Column<DateTime>("timestamptz"), CreatedBy=t.Column<Guid>("uuid"), UpdatedBy=t.Column<Guid>("uuid"), IsDeleted=t.Column<bool>("boolean"), DeletedAt=t.Column<DateTime>("timestamptz") }, constraints: t=> { t.PrimaryKey("PK_PreMissionAssessmentAssets",x=>x.Id); t.ForeignKey("FK_PreMissionAssessmentAssets_PreMissionAssessments_AssessmentId",x=>x.AssessmentId,"PreMissionAssessments","Id",onDelete:ReferentialAction.Cascade); });
        m.CreateTable("PreMissionAssessmentPersonnel", columns: t => new { Id=t.Column<Guid>("uuid"), AssessmentId=t.Column<Guid>("uuid"), UserId=t.Column<Guid>("uuid"), IsEligible=t.Column<bool>("boolean"), Findings=t.Column<string>("jsonb"), CreatedAt=t.Column<DateTime>("timestamptz"), UpdatedAt=t.Column<DateTime>("timestamptz"), CreatedBy=t.Column<Guid>("uuid"), UpdatedBy=t.Column<Guid>("uuid"), IsDeleted=t.Column<bool>("boolean"), DeletedAt=t.Column<DateTime>("timestamptz") }, constraints: t=> { t.PrimaryKey("PK_PreMissionAssessmentPersonnel",x=>x.Id); t.ForeignKey("FK_PreMissionAssessmentPersonnel_PreMissionAssessments_AssessmentId",x=>x.AssessmentId,"PreMissionAssessments","Id",onDelete:ReferentialAction.Cascade); t.ForeignKey("FK_PreMissionAssessmentPersonnel_Users_UserId",x=>x.UserId,"Users","Id",onDelete:ReferentialAction.Restrict); });
        m.CreateTable("DroneTechnicalInspections", columns: t => new { Id=t.Column<Guid>("uuid"), DroneId=t.Column<Guid>("uuid"), Status=t.Column<string>("text"), Health=t.Column<string>("text"), SourceType=t.Column<string>("text"), SourceVersion=t.Column<string>("text"), RawSnapshot=t.Column<string>("jsonb"), CompletedAt=t.Column<DateTime>("timestamptz"), ValidUntil=t.Column<DateTime>("timestamptz"), CreatedAt=t.Column<DateTime>("timestamptz"), UpdatedAt=t.Column<DateTime>("timestamptz"), CreatedBy=t.Column<Guid>("uuid"), UpdatedBy=t.Column<Guid>("uuid"), IsDeleted=t.Column<bool>("boolean"), DeletedAt=t.Column<DateTime>("timestamptz") }, constraints: t=> { t.PrimaryKey("PK_DroneTechnicalInspections",x=>x.Id); t.ForeignKey("FK_DroneTechnicalInspections_UAVs_DroneId",x=>x.DroneId,"UAVs","Id",onDelete:ReferentialAction.Cascade); });
        m.CreateTable("PreMissionAssessmentDrones", columns: t => new { Id=t.Column<Guid>("uuid"), AssessmentId=t.Column<Guid>("uuid"), DroneId=t.Column<Guid>("uuid"), IsEligible=t.Column<bool>("boolean"), TechnicalHealth=t.Column<string>("text"), TechnicalInspectionId=t.Column<Guid>("uuid"), CreatedAt=t.Column<DateTime>("timestamptz"), UpdatedAt=t.Column<DateTime>("timestamptz"), CreatedBy=t.Column<Guid>("uuid"), UpdatedBy=t.Column<Guid>("uuid"), IsDeleted=t.Column<bool>("boolean"), DeletedAt=t.Column<DateTime>("timestamptz") }, constraints: t=> { t.PrimaryKey("PK_PreMissionAssessmentDrones",x=>x.Id); t.ForeignKey("FK_PreMissionAssessmentDrones_PreMissionAssessments_AssessmentId",x=>x.AssessmentId,"PreMissionAssessments","Id",onDelete:ReferentialAction.Cascade); t.ForeignKey("FK_PreMissionAssessmentDrones_UAVs_DroneId",x=>x.DroneId,"UAVs","Id",onDelete:ReferentialAction.Restrict); t.ForeignKey("FK_PreMissionAssessmentDrones_DroneTechnicalInspections_TechnicalInspectionId",x=>x.TechnicalInspectionId,"DroneTechnicalInspections","Id",onDelete:ReferentialAction.Restrict); });
        m.CreateTable("DroneTechnicalMetrics", columns: t => new { Id=t.Column<Guid>("uuid"), InspectionId=t.Column<Guid>("uuid"), MetricCode=t.Column<string>("varchar(100)"), NumericValue=t.Column<decimal>("numeric"), Passed=t.Column<bool>("boolean"), Critical=t.Column<bool>("boolean"), ValueText=t.Column<string>("text"), CreatedAt=t.Column<DateTime>("timestamptz"), UpdatedAt=t.Column<DateTime>("timestamptz"), CreatedBy=t.Column<Guid>("uuid"), UpdatedBy=t.Column<Guid>("uuid"), IsDeleted=t.Column<bool>("boolean"), DeletedAt=t.Column<DateTime>("timestamptz") }, constraints: t=> { t.PrimaryKey("PK_DroneTechnicalMetrics",x=>x.Id); t.ForeignKey("FK_DroneTechnicalMetrics_DroneTechnicalInspections_InspectionId",x=>x.InspectionId,"DroneTechnicalInspections","Id",onDelete:ReferentialAction.Cascade); });
        m.CreateIndex("IX_Missions_PreMissionAssessmentId","Missions","PreMissionAssessmentId",unique:true,filter:"\"PreMissionAssessmentId\" IS NOT NULL AND NOT \"IsDeleted\"");
        m.AddForeignKey("FK_Missions_PreMissionAssessments_PreMissionAssessmentId","Missions","PreMissionAssessmentId","PreMissionAssessments","Id",onDelete:ReferentialAction.Restrict);
        m.CreateIndex("IX_PreMissionAssessmentAssets_AssessmentId_AssetId","PreMissionAssessmentAssets",new[]{"AssessmentId","AssetId"},unique:true); m.CreateIndex("IX_PreMissionAssessmentPersonnel_AssessmentId_UserId","PreMissionAssessmentPersonnel",new[]{"AssessmentId","UserId"},unique:true); m.CreateIndex("IX_PreMissionAssessmentDrones_AssessmentId_DroneId","PreMissionAssessmentDrones",new[]{"AssessmentId","DroneId"},unique:true); m.CreateIndex("IX_DroneTechnicalMetrics_InspectionId_MetricCode","DroneTechnicalMetrics",new[]{"InspectionId","MetricCode"},unique:true);
    }
    protected override void Down(MigrationBuilder m) { m.DropTable("DroneTechnicalMetrics"); m.DropTable("PreMissionAssessmentDrones"); m.DropTable("PreMissionAssessmentPersonnel"); m.DropTable("PreMissionAssessmentAssets"); m.DropTable("DroneTechnicalInspections"); m.DropForeignKey("FK_Missions_PreMissionAssessments_PreMissionAssessmentId","Missions"); m.DropTable("PreMissionAssessments"); m.DropIndex("IX_Missions_PreMissionAssessmentId","Missions"); m.DropColumn("PreMissionAssessmentId","Missions"); m.DropColumn("OperationalStatus","UAVs"); m.DropColumn("TechnicalHealth","UAVs"); }
}
