// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UavPms.OperationsService.Infrastructure.Persistence;

#nullable disable

namespace UavPms.OperationsService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.AIAnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnalysisType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("MissionId");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasFilter("\"SourceEventId\" IS NOT NULL");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("MediaId", "AnalysisType", "ModelName")
                        .IsUnique()
                        .HasDatabaseName("IX_AIAnalysisRequests_ActiveLogicalAnalysis")
                        .HasFilter("\"MediaId\" IS NOT NULL AND \"IsDeleted\" = false AND \"Status\" IN (0, 1)");

                    b.ToTable("AIAnalysisRequests", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.AlertEscalation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EscalatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EscalatedTo")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("EscalatedBy");

                    b.HasIndex("EscalatedTo");

                    b.ToTable("AlertEscalations", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ComponentCode");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ComponentType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<double>("CurrentHealthScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastInspectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<Guid?>("ManagementUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PowerLineId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TowerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("ManagementUnitId");

                    b.HasIndex("PowerLineId");

                    b.HasIndex("TowerId");

                    b.ToTable("AssetComponents", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.AssetHealthHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveDefectsCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CalculationLog")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("HealthScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetHealthHistories", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.DefectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmergencyClass")
                        .HasColumnType("boolean");

                    b.Property<double>("SeverityWeight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("DefectCategories", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.DetectedAnomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiDetectionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AiSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AnalystId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnalystNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("BoundingBox")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CropUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FrameIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Gps")
                        .HasColumnType("jsonb");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Timestamp")
                        .HasColumnType("double precision");

                    b.Property<string>("TowerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("VideoDuration")
                        .HasColumnType("double precision");

                    b.Property<double?>("VideoFps")
                        .HasColumnType("double precision");

                    b.Property<int?>("VideoHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("VideoWidth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalystId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MediaId", "AiDetectionId")
                        .IsUnique()
                        .HasFilter("\"AiDetectionId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.ToTable("DetectedAnomalies", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.EmergencyAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnomalyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryLatencySeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnomalyId");

                    b.HasIndex("AssetId");

                    b.HasIndex("MissionId");

                    b.ToTable("EmergencyAlerts", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.IncidentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("MissionId");

                    b.HasIndex("ReportedBy");

                    b.ToTable("IncidentReports", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.InspectionMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Geometry>("CaptureLocation")
                        .HasColumnType("geometry");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TowerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("MissionId");

                    b.HasIndex("TowerId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("InspectionMedia", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.LineSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromAssetId")
                        .HasColumnType("uuid");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry(Geometry,4326)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PowerLineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromAssetId");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("PowerLineId");

                    b.HasIndex("ToAssetId");

                    b.ToTable("LineSegments", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MaintenanceProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AfterRepairImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TechnicianNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("MaintenanceProofs", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MaintenanceTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnomalyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnomalyId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.ToTable("MaintenanceTickets", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.ManagementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ManagementUnits", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MaterialLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldObservations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LoggedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("integer");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoggedBy");

                    b.HasIndex("TicketId");

                    b.ToTable("MaterialLogs", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MissionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UavId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InspectorId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("MissionCode")
                        .IsUnique();

                    b.HasIndex("UavId");

                    b.ToTable("Missions", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MissionFlightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlightDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("GpsTrack")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("MaxAltitudeM")
                        .HasColumnType("double precision");

                    b.Property<double>("MinBatteryRecorded")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.ToTable("MissionFlightLogs", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MissionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("MissionId", "AssetId")
                        .IsUnique();

                    b.ToTable("MissionTargets", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MissionTargetLine", b =>
                {
                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LineAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MissionId", "LineAssetId");

                    b.HasIndex("LineAssetId");

                    b.ToTable("MissionTargetLines", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPushed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PushedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry(Geometry,4326)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("ParentId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Substation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegionAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubstationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("VoltageLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("RegionAssetId");

                    b.ToTable("Substations", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Tower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LineAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TowerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("LineAssetId");

                    b.HasIndex("TowerCode")
                        .IsUnique();

                    b.ToTable("Towers", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.TransmissionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry(Geometry,4326)");

                    b.Property<bool>("IsCriticalEdge")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ManagementUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubstationAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("VoltageLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("LineName")
                        .IsUnique();

                    b.HasIndex("ManagementUnitId");

                    b.HasIndex("SubstationAssetId");

                    b.ToTable("TransmissionLines", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.TrustedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrustedDevices", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Uav", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Point>("CurrentLocation")
                        .HasColumnType("geometry");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMaintenanceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UavCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CurrentLocation"), "gist");

                    b.HasIndex("UavCode")
                        .IsUnique();

                    b.ToTable("UAVs", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("UavPms.Shared.Contracts.Events.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageType", "OccurredAt")
                        .HasFilter("\"PublishedAt\" IS NULL AND \"IsDeleted\" = false");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.AIAnalysisRequest", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.InspectionMedia", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Media");

                    b.Navigation("Mission");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.AlertEscalation", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.EmergencyAlert", "Alert")
                        .WithMany("AlertEscalations")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "EscalatedByUser")
                        .WithMany()
                        .HasForeignKey("EscalatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "EscalatedToUser")
                        .WithMany()
                        .HasForeignKey("EscalatedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("EscalatedByUser");

                    b.Navigation("EscalatedToUser");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Asset", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.ManagementUnit", "ManagementUnit")
                        .WithMany("Assets")
                        .HasForeignKey("ManagementUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.TransmissionLine", "PowerLine")
                        .WithMany("Assets")
                        .HasForeignKey("PowerLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Tower", "Tower")
                        .WithMany("Assets")
                        .HasForeignKey("TowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManagementUnit");

                    b.Navigation("PowerLine");

                    b.Navigation("Tower");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.AssetHealthHistory", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "Asset")
                        .WithMany("HealthHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.DetectedAnomaly", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Analyst")
                        .WithMany()
                        .HasForeignKey("AnalystId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "Asset")
                        .WithMany("DetectedAnomalies")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.DefectCategory", "Category")
                        .WithMany("DetectedAnomalies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.InspectionMedia", "Media")
                        .WithMany("DetectedAnomalies")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analyst");

                    b.Navigation("Asset");

                    b.Navigation("Category");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.EmergencyAlert", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.DetectedAnomaly", "Anomaly")
                        .WithMany("EmergencyAlerts")
                        .HasForeignKey("AnomalyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "Asset")
                        .WithMany("EmergencyAlerts")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Mission", "Mission")
                        .WithMany("EmergencyAlerts")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anomaly");

                    b.Navigation("Asset");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.IncidentReport", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "Asset")
                        .WithMany("IncidentReports")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Mission", "Mission")
                        .WithMany("IncidentReports")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Mission");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.InspectionMedia", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "Asset")
                        .WithMany("InspectionMedias")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Mission", "Mission")
                        .WithMany("InspectionMedias")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Tower", "Tower")
                        .WithMany()
                        .HasForeignKey("TowerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("Mission");

                    b.Navigation("Tower");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.LineSegment", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "FromAsset")
                        .WithMany()
                        .HasForeignKey("FromAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.TransmissionLine", "PowerLine")
                        .WithMany("LineSegments")
                        .HasForeignKey("PowerLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "ToAsset")
                        .WithMany()
                        .HasForeignKey("ToAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromAsset");

                    b.Navigation("PowerLine");

                    b.Navigation("ToAsset");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MaintenanceProof", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.MaintenanceTicket", "Ticket")
                        .WithMany("MaintenanceProofs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MaintenanceTicket", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.DetectedAnomaly", "Anomaly")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("AnomalyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "Asset")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anomaly");

                    b.Navigation("Asset");

                    b.Navigation("Manager");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.ManagementUnit", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.ManagementUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MaterialLog", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Logger")
                        .WithMany()
                        .HasForeignKey("LoggedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.MaintenanceTicket", "Ticket")
                        .WithMany("MaterialLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logger");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Mission", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Uav", "Uav")
                        .WithMany("Missions")
                        .HasForeignKey("UavId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inspector");

                    b.Navigation("Manager");

                    b.Navigation("Uav");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MissionFlightLog", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Mission", "Mission")
                        .WithMany("MissionFlightLogs")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MissionTarget", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Asset", "Asset")
                        .WithMany("MissionTargets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Mission", "Mission")
                        .WithMany("MissionTargets")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MissionTargetLine", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.TransmissionLine", "TransmissionLine")
                        .WithMany("MissionTargetLines")
                        .HasForeignKey("LineAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Mission", "Mission")
                        .WithMany("MissionTargetLines")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("TransmissionLine");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Notification", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Region", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Region", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Substation", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Region", "Region")
                        .WithMany("Substations")
                        .HasForeignKey("RegionAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Tower", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.TransmissionLine", "TransmissionLine")
                        .WithMany("Towers")
                        .HasForeignKey("LineAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransmissionLine");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.TransmissionLine", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.ManagementUnit", "ManagementUnit")
                        .WithMany("PowerLines")
                        .HasForeignKey("ManagementUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UavPms.OperationsService.Domain.Entities.Substation", "Substation")
                        .WithMany("TransmissionLines")
                        .HasForeignKey("SubstationAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManagementUnit");

                    b.Navigation("Substation");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.TrustedDevice", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("UavPms.OperationsService.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UavPms.OperationsService.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Asset", b =>
                {
                    b.Navigation("DetectedAnomalies");

                    b.Navigation("EmergencyAlerts");

                    b.Navigation("HealthHistories");

                    b.Navigation("IncidentReports");

                    b.Navigation("InspectionMedias");

                    b.Navigation("MaintenanceTickets");

                    b.Navigation("MissionTargets");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.DefectCategory", b =>
                {
                    b.Navigation("DetectedAnomalies");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.DetectedAnomaly", b =>
                {
                    b.Navigation("EmergencyAlerts");

                    b.Navigation("MaintenanceTickets");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.EmergencyAlert", b =>
                {
                    b.Navigation("AlertEscalations");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.InspectionMedia", b =>
                {
                    b.Navigation("DetectedAnomalies");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.MaintenanceTicket", b =>
                {
                    b.Navigation("MaintenanceProofs");

                    b.Navigation("MaterialLogs");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.ManagementUnit", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Children");

                    b.Navigation("PowerLines");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Mission", b =>
                {
                    b.Navigation("EmergencyAlerts");

                    b.Navigation("IncidentReports");

                    b.Navigation("InspectionMedias");

                    b.Navigation("MissionFlightLogs");

                    b.Navigation("MissionTargetLines");

                    b.Navigation("MissionTargets");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Region", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Substations");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Substation", b =>
                {
                    b.Navigation("TransmissionLines");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Tower", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.TransmissionLine", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("LineSegments");

                    b.Navigation("MissionTargetLines");

                    b.Navigation("Towers");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.Uav", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("UavPms.OperationsService.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
