<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="FluentAssertions" Version="6.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.16" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\AIInspectionService\UavPms.AIInspectionService.Application\UavPms.AIInspectionService.Application.csproj" />
    <ProjectReference Include="..\Services\AIInspectionService\UavPms.AIInspectionService.Domain\UavPms.AIInspectionService.Domain.csproj" />
    <ProjectReference Include="..\Services\AIInspectionService\UavPms.AIInspectionService.Infrastructure\UavPms.AIInspectionService.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\IdentityService\UavPms.IdentityService.Application\UavPms.IdentityService.Application.csproj" />
    <ProjectReference Include="..\Services\IdentityService\UavPms.IdentityService.Domain\UavPms.IdentityService.Domain.csproj" />
    <ProjectReference Include="..\Services\IdentityService\UavPms.IdentityService.Infrastructure\UavPms.IdentityService.Infrastructure.csproj" />
    <ProjectReference Include="..\Services\NotificationService\UavPms.NotificationService.csproj" />
    <ProjectReference Include="..\Services\OperationsService\UavPms.OperationsService.Application\UavPms.OperationsService.Application.csproj" />
    <ProjectReference Include="..\Services\OperationsService\UavPms.OperationsService.Domain\UavPms.OperationsService.Domain.csproj" />
    <ProjectReference Include="..\Services\OperationsService\UavPms.OperationsService.Infrastructure\UavPms.OperationsService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
